services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio_container
    restart: always
    ports:
      - "9000:9000"      # S3
      - "9001:9001"      # Web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit_container
    restart: always
    ports:
      - "1025:1025"  # PORTA PARA O ENV
      - "8025:8025"  #WEB

volumes:
  mysql_data:
  postgres_data:
  minio_data: